### ISSUE TITLE
Use http-core or 723x?

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/draft-polli-resource-digests-http#18]
## Task

Should we base on 723x or [http-core](https://github.com/httpwg/http-core) ?
Are there changes in http-core that modify or improve Digest definition (eg. terminology, ...)?

**Comment by LPardue** [comment]
Part of helping to make this decision will be to understand if there are changes in HTTP core that modify or improve upon anything we refer to in this draft. For example, improved definition of terms we import etc.

**Comment by ioggstream** [comment]
moved to https://github.com/httpwg/http-extensions/issues/854
