### ISSUE TITLE
Create a threat model

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/draft-polli-resource-digests-http#29]
## I wish

A threat model for `Digest`.

## Questions

- is this useful/required?
- should this go into Security Considerations or in another document?

**Comment by LPardue** [comment]
Trying to understand if this is an issue that requires working group input on. Do you think this needs to go into the spec or is it a means to help articulate the problem space (that we could put in some slides or a wiki).

**Comment by ioggstream** [comment]
moved to https://github.com/httpwg/http-extensions/issues/852
