### ISSUE TITLE
GitHub pages is a little messed up

### ISSUE THREAD

**Issue by LPardue** [ioggstream/draft-polli-resource-digests-http#3]
Oops. 

Because I forked the repo, the way GitHub pages works to self-host a HTML version of the I-D is a little messed up. This repo points at mine, which is not the correct source of truth. 

I think what we need to do is add a gh-pages branch to the master repo, I can submit the PR to update it with files and update README.md to point to your HTML.

Sounds ok?

**Comment by ioggstream** [comment]
Sure, will do! Sorry to bother you for that kind of stuff!

**Comment by LPardue** [comment]
No problem at all, I think the root problem is now fixed.

Ideally, we run `make ghpages` in your repository everytime `master` is updated. This will push a change to your repos gh-pages branch reflecting all the latest updates. Since I don't have write privileges to your repo (which is fine) I can't do that step.

We can probably get away just running it for a version that we are happy to baseline and share.

**Comment by ioggstream** [comment]
CI should update it here https://ioggstream.github.io/draft-polli-resource-digests-http/draft-polli-resource-digests-http.html

**Comment by LPardue** [comment]
great!
