### ISSUE TITLE
Investigate the usage of PATCH

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/draft-polli-resource-digests-http#4]
## About PATCH

1- `PATCH` is not in http 723x
2- `PATCH` media type should be something like https://tools.ietf.org/html/rfc7396 because 
servers SHOULD NOT assume PATCH semantics for generic
   media types that don't define them, such as "application/xml" or
   "application/json".  Doing so will cause interoperability issues,
   because the semantics of PATCH become specific to that resource,
   rather than general.
3- it's difficult to use patch + checksums, like @LPardue said

## Hypothesis

1- warn people about PATCH+Digest
2- don't forbid PATCH+Digest

**Comment by LPardue** [comment]
I'd like to understand more from implementers and users of PATCH. On the one hand it seems like it could be useful to validate the PATCH request body *before* applying it to the resource, on the other hand I don't know if the current expression of Digest support that use.

**Comment by ioggstream** [comment]
moved to https://github.com/httpwg/http-extensions/issues/853
