### ISSUE TITLE
DISCOURAGES is not an RFC2119 keyword

### ISSUE THREAD

**Issue by LPardue** [ioggstream/draft-polli-resource-digests-http#8]
> This RFC DISCOURAGES the use of MD5 algorithm for security reasons.

DISCOURAGES is not a 2119 keyword and therefore has little normative affect.

Suggestion would be to replace the sentence with:

"The use of the MD5 algorithm is NOT RECOMMENDED for security reasons."

However, this just a stop gap because for "security reasons" is not qualified with discussion or citation. The final document will need to address this but I think we can live with things for the time being.

**Comment by ioggstream** [comment]
Thanks for the hint. We can create an issue for the MD5 story.

**Comment by ioggstream** [comment]
fixed in 53f3dc8
